name: Modelops deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: adsoft/aiops:latest

    steps:
      # 1️⃣ Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2️⃣ Entrenar el modelo
      - name: Train TensorFlow model
        run: python3 linear-model.py

      # 3️⃣ Login a Docker Hub
      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # 4️⃣ Crear contenedor base con TensorFlow Serving
      - name: Download and run the Docker base image
        run: docker run -d --name serving_base tensorflow/serving

      # 5️⃣ Copiar modelo entrenado al contenedor
      - name: Copy model to the Docker image
        run: docker cp linear-model serving_base:/models/linear-model

      # 6️⃣ Construir imagen personalizada
      - name: Build the custom Docker image
        run: docker commit --change "ENV MODEL_NAME linear-model" serving_base ${{ secrets.DOCKER_USER }}/tensorflow-linear-model:${{ github.sha }}

      # 7️⃣ Subir imagen a Docker Hub
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USER }}/tensorflow-linear-model:${{ github.sha }}

      # 8️⃣ Desplegar en Render
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-XXXXXXXX?key=${{ secrets.RENDER_API_KEY }}
